### ISSUE TITLE
有个类似框架rpc-java，考虑合并吗？

### ISSUE THREAD

**Issue by wenweihu86** [smallnest/rpcx-java#1]
我之前写了个基于netty的rpc框架，支持多协议扩展，考虑合并吗？
https://github.com/wenweihu86/rpc-java

**Comment by smallnest** [comment]
谢谢推荐。

这个项目主要还是做rpcx的java client，而不是做一个java rpc框架。
第一步是实现raw java client,可以用在java和android项目中。
第二步是做netty的codec插件，方便netty集成
第三步是做服务治理的fat rpcx client。

所以目标可能不同，但是有很多可以借鉴的地方，比如协议解析和netty codec，多谢推荐。
如果你有好的想法，也欢迎comment
