### ISSUE TITLE
client.call throw Exception for a while

### ISSUE THREAD

**Issue by longkeyy** [smallnest/rpcx-java#2]
Client client = new Client();
        client.connect("127.0.0.1", 8972);
        long start = System.currentTimeMillis();
        for (int i = 0; i < 10000; i++) {
            Message res = client.call(getRequest("k" + i % 10));
            System.out.println(res.metadata.isEmpty());
            System.out.println(new String(res.payload) + " ============ " + i);
        }
        long end = System.currentTimeMillis();
        System.out.println("cost:" + (end - start));

throw Exception for a while

Exception in thread "main" java.util.concurrent.TimeoutException
	at java.util.concurrent.CompletableFuture.timedGet(CompletableFuture.java:1771)
	at java.util.concurrent.CompletableFuture.get(CompletableFuture.java:1915)
	at com.colobu.rpcx.client.Client.call(Client.java:130)
	at RpcxClientTest.call(RpcxClientTest.java:36)
	at RpcxClientTest.main(RpcxClientTest.java:49)

**Comment by smallnest** [comment]
Do you have set different Seq for each requests (how do you implement getRequest?)?

**Comment by longkeyy** [comment]
public static Message getRequest(String key) {
        Message req = new Message("echo", "Echo");
        req.setVersion((byte) 0);
        req.setMessageType(MessageType.Request);
        req.setHeartbeat(false);
        req.setOneway(false);
        req.setCompressType(CompressType.None);
        req.setSerializeType(SerializeType.SerializeNone);
        req.setSeq(System.currentTimeMillis());

        req.metadata.put("test", "1234");

        req.payload = ("images/" + key).getBytes();
        return req;
    }

**Comment by longkeyy** [comment]
change seq from System.currentTimeMillis() to  req.setSeq(System.nanoTime());
